# === Gmail SMTP ===
spring.mail.host=smtp.yandex.ru
spring.mail.port=465
spring.mail.username=${YANDEX_USERNAME}
spring.mail.password=${YANDEX_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.yandex.ru

# === Оставляю тут профиль для отправки ===
app.mail.from=${MAIL_FROM}

# === PUSH (Telegram) ===
telegram.bot-token=${TELEGRAM_BOT_TOKEN}
telegram.chat-id=${TELEGRAM_CHAT_ID}

# === SMS ===
sms.provider-url=${SMS_PROVIDER_URL}
sms.api-key=${SMS_API_KEY}

# === Логирование ===
logging.level.com.zhulikov.project.notificationservice=INFO
logging.level.org.springframework.boot.autoconfigure.flyway=WARN