spring.application.name=Notification-Service

# === Профиль по умолчанию ===
spring.profiles.active=dev

# === PostgreSQL ===
spring.datasource.url=jdbc:postgresql://localhost:5433/notification_service
spring.datasource.username=admin
spring.datasource.password=pass

# === JPA ===
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# === Flyway ===
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# === RabbitMQ ===
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=pass

# === Retry ===
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=5000
spring.rabbitmq.listener.simple.retry.multiplier=2.0
spring.rabbitmq.listener.simple.retry.max-interval=300000

# === Server ===
server.port=8081

# === Actuator ===
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# === Logging ===
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG