# === Gmail SMTP ===
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# === PUSH (Telegram) ===
telegram.bot-token=${TELEGRAM_BOT_TOKEN}
telegram.chat-id=${TELEGRAM_CHAT_ID}

# === SMS ===
sms.provider-url=${SMS_PROVIDER_URL}
sms.api-key=${SMS_API_KEY}

# === Логирование ===
logging.level.com.zhulikov.project.notificationservice=INFO
logging.level.org.springframework.boot.autoconfigure.flyway=WARN