# === Mailpit (локальный SMTP) ===
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# === Оставляю тут профиль для отправки ===
app.mail.from=noreply@notification-service.local

# === PUSH (Telegram) (dev не отправляет) ===
telegram.bot-token=
telegram.chat-id=

# === SMS (dev не отправляет) ===
sms.provider-url=
sms.api-key=

# === Логирование ===
logging.level.com.zhulikov.project.notificationservice=DEBUG